<!doctype html>
<html>
<head>
  <title><?= $this->title ?></title>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.2.0/build/cssreset/reset-min.css">
  <link rel="stylesheet" type="text/css" href="/styles/base.css">
</head>
<body>
  <h1><?= $this->title ?></h1>
  <div id="content">
<?= $this->pageContent ?>
  </div>
  <div id="sidebar">
    <p class="right"><a href="index.php">Back to list view</a></p>
<?= new Template(TPL . "/submit.phtml"); ?>
  </div>
  <p id="footer">Post what you want. <a href="http://github.com/rmasters/wall">We're on github</a> too.</p>
</body>
</html>
