<?php if (count($this->posts) != 0): ?>
<?php foreach ($this->posts as $post): ?>
<div class="post">
<p class="author"><?= $post->name ?> posted <a href="index.php?id=<?= $post->id ?>" title="<?= date("r", $post->posted) ?>"><?= humanTime($post->posted) ?></a>:</p>
<blockquote class="content">
  <?php if ($post->preformatted): ?><pre><?php else: ?><p><?php endif; ?><?= formatMessage($post->content) ?><?php if ($post->preformatted): ?></pre><?php else: ?></p><?php endif; ?>
  </blockquote>
</div>
<?php endforeach; ?>
<?php else: ?>
<p>No posts in the database!</p>
<?php endif; ?>
<p class="pagination">
<?php if ($this->page != 1): ?><a href="?page=1">Start</a><?php endif; ?> Page <?= $this->page ?> <?php if (count($this->posts) == $this->perPage): ?><a href="?page=<?= $this->page + 1 ?>">Next</a><?php endif; ?></p>
