<h2>Submit a post</h2>
<form action="submit.php" method="post">
  <p><label for="name">Your name (optional)</label><input type="text" name="name" id="name"></p>
  <p><label for="content">Post content</label><textarea name="content" id="content"></textarea></p>
  <p><label for="preformatted">This is code or ASCii art<input type="checkbox" name="preformatted" id="preformatted"></label></p>
  <p><input type="submit" value="Post"></p>
</form>
